In [1]:
import pandas as pd

In [2]:
df_de_para_ims_sammed = pd.read_excel('De_Para_IMS_SAMMED.xlsx')

In [12]:
df_lab_stopwrds = pd.read_csv('stopwrds_lab.csv',names= ['stopwords'])

In [14]:
df_lab_stopwrds

    stopwords
0         A1F
1         A3N
2         A4H
3         A9N
4         AA0
5         AAI
6         AB1
7         AB3
8         ABT
9         AEE
10        AES
11        AH_
12        ALC
13        ALL
14        AOB
15        APS
16        ATV
17        ATX
18        AV7
19        AZN
20        B0B
21        B2I
22        B4I
23        BAG
24        BAL
25        BAX
26        BCN
27        BDB
28        BF8
29        BFR
..        ...
164       SDZ
165       SIN
166       SNV
167       SOB
168       SP0
169       SSW
170       STF
171       SUD
172       SUV
173       SVR
174       SVS
175       S_A
176       S_S
177       TAK
178       TEV
179       TKS
180       TNT
181       TPQ
182       TSK
183       TTB
184       UCI
185       U_E
186       U_Q
187       VAP
188       VCY
189       VLT
190       VTM
191       WPR
192       ZAM
193       ZD1

[194 rows x 1 columns]

In [15]:
lista_prods = list(df_de_para_ims_sammed['prod'])

In [ ]:
lista_prods_processada = [x.]